version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "hello-world-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-4h9lffzdpzzw"
s3_prefix = "hello-world-app"
region = "us-east-1"
profile = "itsandbox-cfservice"
capabilities = "CAPABILITY_IAM"
image_repositories = ["HelloWorldFunction=804034162148.dkr.ecr.us-east-1.amazonaws.com/demo-app-hello-world"]
parameter_overrides = "SecurityGroupIds=\"sg-0c625e6cfa9c17e33\" SubnetIDs=\"subnet-0aa9c73cbf165d4a0,subnet-07d44829944aea30f,subnet-05c3b8e6ce902c43f\" EFSpath=\"/mnt/efs\" AccessPointARN=\"arn:aws:elasticfilesystem:us-east-1:804034162148:access-point/fsap-040079bb4ea6261fd\""
