# Based off of https://github.com/aws-samples/aws-lambda-efs-samples
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lambda to run a docker container
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Container Settings
        Parameters:
          - ImageUri
          - EntryPoint
          - Command
          - WorkingDirectory
          - MemorySize
      - Label:
          default: Execution Trigger
        Parameters:
          - EnableSchedule
          - Schedule
      - Label:
          default: EFS
        Parameters:
          - SecurityGroupIds
          - SubnetIDs
          - AccessPointARN
          - EFSpath
Parameters:
  SecurityGroupIds:
    Type: CommaDelimitedList
  SubnetIDs:
    Type: CommaDelimitedList
    Description: The list of SubnetIDs in your Virtual Private Cloud (VPC)
  EFSpath:
    Type: String
    Default: /mnt/efs
  AccessPointARN:
    Type: String
    Description: Access point ARN
  MemorySize:
    Type: Number
    MinValue: 128
    MaxValue: 10240
    Default: 128
    Description: >
      The amount of memory available to the function at runtime. Increasing the function's
      memory also increases its CPU allocation.
  ImageUri:
    Type: String
    Description: >
      The URI of the Amazon ECR) repository for the Lambda function's container image.
      Example: 111111111.dkr.ecr.us-east-1.amazonaws.com/MY-DOCKER:latest
  EntryPoint:
    Type: String
    Default: ""
    Description: (Optional) The entry point to the application in the docker container
  Command:
    Type: CommaDelimitedList
    Default: ""
    Description: (Optional) Command separated list of parameters to pass in with docker ENTRYPOINT
  WorkingDirectory:
    Type: String
    Default: ""
    Description: (Optional) The working directory for the docker container
  EnableSchedule:
    Description: >
      true to run on a schedule, false to disable. If enabled a valid Schedule must be provided
    Type: String
    Default: false
    AllowedValues:
      - true
      - false
  Schedule:
    Description: >
      Schedule to execute the docker, can be a rate or a cron schedule. Format at
      https://docs.aws.amazon.com/AmazonCloudWatch/latest/events/ScheduledEvents.html
    Type: String
    Default: cron(0 09 ? * MON *)  # Run every Monday at 9am
    ConstraintDescription: "Use schedule format: https://docs.aws.amazon.com/AmazonCloudWatch/latest/events/ScheduledEvents.html"
Conditions:
  HasEntryPoint: !Not [!Equals [!Ref EntryPoint, ""]]
  HasCommand: !Not
    - !Equals
      - !Join ["", !Ref Command]
      - ''
  HasWorkingDirectory: !Not [!Equals [!Ref WorkingDirectory, ""]]
Resources:
  EfsPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AmazonElasticFileSystemClientFullAccess
            Effect: Allow
            Action:
              - elasticfilesystem:ClientMount
              - elasticfilesystem:ClientRootAccess
              - elasticfilesystem:ClientWrite
              - elasticfilesystem:DescribeMountTargets
            Resource: "*"
  ExecutionPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AWSLambdaVPCAccessExecutionRole
            Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
              - ec2:CreateNetworkInterface
              - ec2:DescribeNetworkInterfaces
              - ec2:DeleteNetworkInterface
            Resource: "*"
  DockerRunnerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 900
      PackageType: Image
      ImageUri: !Ref ImageUri
      ImageConfig:
        Command: !If [HasCommand, !Ref Command, !Ref 'AWS::NoValue']
        EntryPoint: !If [HasEntryPoint, !Ref EntryPoint, !Ref 'AWS::NoValue']
        WorkingDirectory: !If [HasWorkingDirectory, !Ref WorkingDirectory, !Ref 'AWS::NoValue']
      MemorySize: !Ref MemorySize
      Environment:
        Variables:
          EFS_PATH: !Ref EFSpath
      Events:
        RecurringSchedule:
          Type: Schedule
          Properties:
            Schedule: !Ref Schedule
            Enabled: !Ref EnableSchedule
        DockerRunner:
          Type: Api
          Properties:
            Path: /run
            Method: get
      VpcConfig:
        SecurityGroupIds: !Ref SecurityGroupIds
        SubnetIds: !Ref SubnetIDs
      FileSystemConfigs:
        - Arn: !Ref AccessPointARN
          LocalMountPath: !Ref EFSpath
      Policies:
        - !Ref EfsPolicy
        - !Ref ExecutionPolicy
Outputs:
  DockerRunnerApi:
    Description: "API Gateway endpoint URL for Prod stage for Docker Runner function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/run/"
  DockerRunnerFunction:
    Description: "Docker Runner Lambda Function ARN"
    Value: !GetAtt DockerRunnerFunction.Arn
  DockerRunnerFunctionIamRole:
    Description: "Implicit IAM Role created for Docker Runner function"
    Value: !GetAtt DockerRunnerFunctionRole.Arn
